VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "wsBasic"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Option Explicit

Public Property Get celArrayToRangeTarget() As Range:   Set celArrayToRangeTarget = Me.Range("celArrayToRangeTarget"):  End Property
Public Property Get rngArrayToRangeTarget() As Range:   Set rngArrayToRangeTarget = Me.Range("rngArrayToRangeTarget"):  End Property

