VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "wsBasic"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Option Explicit

Public Property Get celArryAsRangeTarget() As Range:   Set celArryAsRangeTarget = Me.Range("celArryAsRangeTarget"):  End Property
Public Property Get rngArryAsRangeTarget() As Range:   Set rngArryAsRangeTarget = Me.Range("rngArryAsRangeTarget"):  End Property

